<a href="https://colab.research.google.com/github/kvinne-anc/Data-Science-Notebooks/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Lambda School Data Science - Intro to Python  
---
# 05 - Numpy
---



##STOP! BEFORE GOING ANY FURTHER...  


1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to "FIRSTNAME_LASTNAME_1_2"  

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and submit. Be sure to do this for ***every*** assignment!



### Import Numpy as Np

In [ ]:
import numpy as np
import numpy as np



In [ ]:
np.random.randint(100, size=(3,5)) 

array([[39, 75, 16, 58, 41],
       [58, 69, 80, 10, 72],
       [80, 82,  8, 25, 42]])

### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [ ]:
array_a = np.random.randint(100, size=(3,5)) 
array_a 


array([[52, 31,  4, 82, 46],
       [54, 88, 71, 12, 95],
       [40, 99, 98, 24, 52]])

### Array practice
Run each of these in their own code cell and comment it accordingly:

*  Return the first row
*  Return the last column
*  Return the third column values from the 4th and 5th rows
*  Multiply every value in the array by 2
*  Divide every value by 3
*  Increase the values in the first row by 12
* Calculate the mean of the first column
* Calculate the median of the array _after_ removing the 2 smallest values in the array
* Calculate the standard deviation of the first 3 rows
* Return values in the second column greater than 25
* Return values in the array under 40

In [ ]:
# Return the first row:

In [ ]:
print(array_a[1]) 





[54 88 71 12 95]


In [ ]:
# return the last column

In [ ]:
print(array_a[0,4]) 
print(array_a[1,4]) 
print(array_a[2,4]) 


46
95
52


In [ ]:
print(array_a[2,3])
print(array_a[2,4])


24
52


I've just realised I switched the 3 and 5 in the initial, so I'm carrying on this way and printing 4th and 5th row 3. 


Multiply every value in the array by 2:


In [ ]:
array_a * 2 

array([[104,  62,   8, 164,  92],
       [108, 176, 142,  24, 190],
       [ 80, 198, 196,  48, 104]])

Divide by 3 (not clear whether original array or resulting array... I will use original.


In [ ]:
array_a / 3 

array([[17.33333333, 10.33333333,  1.33333333, 27.33333333, 15.33333333],
       [18.        , 29.33333333, 23.66666667,  4.        , 31.66666667],
       [13.33333333, 33.        , 32.66666667,  8.        , 17.33333333]])

Increase the values in the first row by 12
 

In [ ]:
array_a[0] + 12 

array([64, 43, 16, 94, 58])

Calculate the mean of the first column 


In [ ]:
np.mean(array_a)

56.53333333333333

I can't seem to get it to do the first column, it doesn't make sense and no matter how I try to index the values it doesn't want to compute.



Calculate the median of the array 


In [ ]:
np.median(array_a)


52.0

In [ ]:
np.std(array_a)

30.260792381488553

Return values greater than 25 in the 2nd row


In [ ]:
print(array_a[1]>25) 


[ True  True  True False  True]


In [ ]:
array_a[array_a > 25] 

array([52, 31, 82, 46, 54, 88, 71, 95, 40, 99, 98, 52])

Return values under 40 in the array 


In [ ]:
print(array_a < 40)
 

[[False  True  True False False]
 [False False False  True False]
 [False False False  True False]]


In [ ]:
array_a[array_a < 40]



array([31,  4, 12, 24])